language: objective-c
osx_image: xcode10

addons:
  homebrew:
    update: true
    brewfile: true

cache: 
  directories:
  - Carthage
  - vendor/bundle

before_install:
  - carthage bootstrap --cache-builds --platform iOS

script:
  - xcodebuild -project Lithium.xcodeproj -scheme Lithium -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build
